site_name: NetBox Cloud Documentation
theme:
  name: material
  favicon: images/social-square.png
  logo: images/social-square.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.prune
    - search.suggest
    # - toc.integrate
markdown_extensions:
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3
plugins:
  - search
nav:
  - Home: index.md
  - Getting Started: "NetBox Cloud/getting-started-with-nbc.md"
  - Guides:
      - Migrating to NetBox Cloud: "NetBox Cloud/migrating-to-netbox-cloud.md"
  - Administration Console:
      - Admin Console Overview: "Administration Console/admin-console-overview.md"
      - Setting up Admin Console Access: "Administration Console/admin-console-access.md"
      - Upgrading NetBox Cloud: "Administration Console/upgrading-nbc.md"
      - Configuring Azure AD SSO: "Administration Console/azure-ad-sso_setup.md"
      - Configuring Ingress Allow Lists: "Administration Console/configuring_ingress_allow_lists.md"
      - Managing Database Snapshots: "Administration Console/managing-database-snapshots.md"

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://netboxlabs.com
    - icon: octicons/mail-24
      link: "mailto:support@netboxlabs.com"
  analytics:
    provider: google
    property: G-Q107GMDTJM
copyright: Copyright &copy; 2023 NetBox Labs
